### ISSUE TITLE
Add / Remove Setting

### ISSUE THREAD

**Issue by xJoeyv** [Laravel-Backpack/Settings#45]
Hi,

I just added Settings Package to my BackPack but as far as I can see I cannot add a setting or remove one via the Dashboard... How to?

**Comment by tabacitu** [comment]
Hi @xJoeyv ,

Adding and deleting entries in Settings is intentionally disabled. The recommended way to do that (and the only way) is directly from the database.

That's because, even if you had an interface to add Settings with no web dev skills, you'd still need web dev skills to use them - in your Controllers, Models or Views. So creating an interface for this made no sense - it would still need to be disabled to the Admins, just like Deletion.

Delete is disabled for DB integrity. If you allowed an admin to delete a setting, things might break in your application. Better not to.

Hope it helps.
Cheers!
