### ISSUE TITLE
Can't create a new setting

### ISSUE THREAD

**Issue by mckenziearts** [Laravel-Backpack/Settings#54]
We can't create a new setting. an sql error is generate 

![capture](https://user-images.githubusercontent.com/14105989/31860115-41184e0a-b70d-11e7-8b9e-d642eedd19d9.PNG)

**Comment by lloy0076** [comment]
What were / are you trying to do when you got that error?

**Comment by tabacitu** [comment]
Hi @mckenziearts ,

Inserting settings from the interface is intentionally disabled. Since a setting can only be used by a developer (in code) I think it makes more sense to have this disabled, as they can more easily be added and customized directly in the db. 

What the user can't do can't hurt him :-)

Cheers!
