### ISSUE TITLE
Add tab Field

### ISSUE THREAD

**Issue by willmkt** [Laravel-Backpack/Settings#7]
Is there any way to add a tab field? or a way to edit the views of the settings page?

In a admin where you have multiple configs gets a bit messy listing all in the same page, so it is good to organize it better.

Thanks.

**Comment by tabacitu** [comment]
Hi @willmkt ,

There is currently no tabs functionality for CRUD, but I see your point - for the Settings plugin we could (and maybe should) create a different way of showing the settings and separate them in tabs/accordions/smth like that. Datatables might not be the best way. I personally have not had any projects with that many settings, to feel the need to separate them. But if you do and are doing a different list view for yourself, I'd be happy to merge it into the package. Basically it's just a matter of using a different view than list.blade.php in SettingCrudController::index() and having an extra attribute in your db field definition, say "tab". That's the way to do it.

If you're willing to modify it in a fork so you can make a pull request - that's the way to modify it, as stated above. Otherwise, if you're only making the modifs for your own project, you'll find a quick way to do it below.

The package is designed in such a way that you can easily copy the code in your project and do any modifs you'd like. Here's what you need to do:
- copy-paste the package files ```src/app``` in your respective application folders;
- change the namespace everywhere to match your app (usually in your editor you can do replace all ```Backpack\Settings\app\``` with ```App\```);
- insert the settings routes to your own routes file (in [SettingServiceProvider.php:55-59](https://github.com/Laravel-Backpack/Settings/blob/master/src/SettingsServiceProvider.php#L55-L59));


Cheers!

**Comment by lloy0076** [comment]
@tabacitu - is this still in the works?
